frontend:
  labels:
    app: akkt2-frontend

  deploy:
    name: akkt2-frontenddeploy
    replicas: 1
    containers:
      name: akkt2-frontend
      imagePullPolicy: IfNotPresent
      image: phil4fh/frontservice:latest
      ports:
        containerPort: 80
        name: httpfront

  service:
    name: akkt2-frontend-svc
    type: NodePort
    labels:
      app: akkt2-frontend
    ports:
      name: port-frontend
      port: 3000
      nodePort: 30017

############
backendleft:
  labels:
    app: akkt2-backendleft

  deploy:
    name: backendleft-deploy
    replicas: 1
    containers:
      name: akkt2-backend
      imagePullPolicy: IfNotPresent
      image: phil4fh/leftservice:latest
      ports:
        containerPort: 3000
        name: httpback-left

  service:
    name: akkt2-backendleft-svcs
    type: ClusterIP
    labels:
      app: akkt2-backendleft
    ports:
      name: port-backend
      port: 3000



############
backendright:
  labels:
    app: akkt2-backendright

  deploy:
    name: backendright-deploy
    replicas: 1
    containers:
      name: akkt2-backend
      imagePullPolicy: IfNotPresent
      image: phil4fh/rightservice:latest
      ports:
        containerPort: 3000
        name: httpback-right

  service:
    name: akkt2-backendright-svcs
    type: ClusterIP
    labels:
      app: akkt2-backendright
    ports:
      name: port-backend
      port: 3000
